services:
  - type: web
    name: fauna-animal-detector
    env: python
    runtime: python
    pythonVersion: "3.11.0"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free